apiVersion: v1
kind: ReplicationController
metadata:
  name: mysvc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysvc
    spec:
      containers:
      - name: mysvc
        image: docker.io/olostan/test_svc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1