name: slides_scaling
description: Scaling Macto with Micro
version: 0.0.1
homepage: https://olostan.github.com/
author: Valentyn Shybanov <olostan@gmail.com>

environment:
  sdk: '>=1.23.0 <=2.1.0'

dependencies:
  angular: "^5.0.0"
  dacsslide: any
  js: ^0.6.0
  sass_builder: any
  build_runner: ^0.10.2
  build_web_compilers: '>=0.3.1 <0.5.0'


dev_dependencies:
#  dart_to_js_script_rewriter: ^1.0.1
